modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
#issueTrackerURL="" #optional

[[mods]] #mandatory
    modId="concoctions" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Concoctions" #mandatory
    # updateJSONURL="" #optional
    # displayURL="" #optional
    # logoFile="" #optional
    authors="xevira" #optional
    description='''Brewing on steroids.'''
[[dependencies.concoctions]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.patchouli]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-48,)"
    ordering="NONE"
    side="BOTH"
